services:
  - docker

language: ruby
sudo: false
cache:
  bundler: false
  directories:
    - sunspot/vendor/bundle
    - sunspot_solr/vendor/bundle
    - sunspot_rails/vendor/bundle

before_install:
  - gem install bundler -v 2.1.2

rvm:
  - 2.6.5
  - 2.7.0
  # - ruby-head
  # - rbx-2.0
  # - jruby

jdk:
  - openjdk11

env:
  - GEM=sunspot UPDATE_FORMAT=xml
  - GEM=sunspot UPDATE_FORMAT=json
  - GEM=sunspot_rails UPDATE_FORMAT=xml
  - GEM=sunspot_rails UPDATE_FORMAT=json
  - GEM=sunspot_solr
  - SOLR_MODE=cloud GEM=sunspot_rails

matrix:
  allow_failures:
    - rvm: ruby-head

script:
  - ci/travis.sh
