language: ruby
sudo: required

services:
  - docker

cache:
  bundler: true
  directories:
    - sunspot/vendor/bundle
    - sunspot_rails/vendor/bundle

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.3.1
  - 2.4.3
  - 2.5.0
  - ruby-head
  # - rbx-2.0
  # - jruby

env:
  global:
    - SOLR_VERSION=6.6
    - SOLR_CORE=default
    - SOLR_PORT=8983
  matrix:
    - GEM=sunspot UPDATE_FORMAT=xml
    - GEM=sunspot UPDATE_FORMAT=json
    - GEM=sunspot_rails

before_install:
  # Setting up and running containerized Solr instance
  - sudo chown -R 8983:8983 ci/solr
  - docker pull solr:$SOLR_VERSION
  - docker run -d --name solr -p $SOLR_PORT:8983 -t -v $PWD/ci/solr:/opt/mysolrhome solr:$SOLR_VERSION bin/solr create_core -c $SOLR_CORE -d /opt/mysolrhome
  - docker ps -a
  # Docker Solr issue: https://github.com/docker-solr/docker-solr/issues/100
  - until [ "`docker inspect -f '{{.State.Running}}' solr`" = "true" ]; do sleep 0.5; done
  - export SOLR_ADDRESS=`docker inspect -f '{{.NetworkSettings.IPAddress}}' solr`
  - echo "Docker Solr ip address is $SOLR_ADDRESS"
  - export SOLR_URL="http://$SOLR_ADDRESS:$SOLR_PORT/solr/$SOLR_CORE"
  - echo "Using Solr URL $SOLR_URL"
  # Install Ruby dependencies
  - gem install bundler

matrix:
  allow_failures:
    - rvm: ruby-head

script:
  - ci/travis.sh

