services:
  - docker

language: ruby
sudo: false
cache:
  bundler: false
  directories:
    - sunspot/vendor/bundle
    - sunspot_solr/vendor/bundle
    - sunspot_rails/vendor/bundle

before_install:
  - gem install rubygems-update -v 2.7.8
  - update_rubygems
  - gem install bundler -v 1.17.3

rvm:
  #- 2.1.0
  #- 2.3.8
  #- 2.4.5
  #- 2.5.3
  - 2.6.5
  #- ruby-head
  # - rbx-2.0
  # - jruby

jdk:
  - openjdk8

env:
  - GEM=sunspot UPDATE_FORMAT=xml
  - GEM=sunspot UPDATE_FORMAT=json
  - GEM=sunspot_rails UPDATE_FORMAT=xml
  - GEM=sunspot_rails UPDATE_FORMAT=json
  - GEM=sunspot_solr
  - SOLR_MODE=cloud GEM=sunspot_rails

matrix:
  allow_failures:
    - rvm: ruby-head

script:
  - ci/travis.sh
