language: ruby
sudo: required

services:
  - docker

cache:
  bundler: true
  directories:
    - sunspot/vendor/bundle
    - sunspot_rails/vendor/bundle

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.3.1
  - 2.4.3
  - 2.5.0
  - ruby-head
  # - rbx-2.0
  # - jruby

env:
  global:
    - SOLR_VERSION=6.6
    - SOLR_PORT=8983
  matrix:
    - GEM=sunspot UPDATE_FORMAT=xml
    - GEM=sunspot UPDATE_FORMAT=json
    - GEM=sunspot_rails

before_install:
  # Setting up and running containerized Solr instance
  - chown -R $SOLR_PORT:$SOLR_PORT ci/solr
  - docker pull solr:$SOLR_VERSION
  - docker run -d --name solr -p 127.0.0.1:$SOLR_PORT:8983 -t -v $PWD/ci/solr:/opt/mysolrhome solr:$SOLR_VERSION \
      bin/solr create_core -c default -d /opt/mysolrhome
  - docker ps -a
  # Install Ruby dependencies
  - gem install bundler

matrix:
  allow_failures:
    - rvm: ruby-head

script:
  - ci/travis.sh

