language: ruby
sudo: required

cache:
  bundler: true
  directories:
    - sunspot/vendor/bundle
    - sunspot_rails/vendor/bundle

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.3.1
  - 2.4.3
  - 2.5.0
  - ruby-head
  # - rbx-2.0
  # - jruby

env:
  global:
    - SOLR_VERSION=6.6
  matrix:
    - GEM=sunspot UPDATE_FORMAT=xml
    - GEM=sunspot UPDATE_FORMAT=json
    - GEM=sunspot_rails

before_install:
  # Setting up and running containerized Solr instance
  - docker pull solr:$SOLR_VERSION
  - docker run -d --name solr -p 8983:8983 -t -v $PWD/ci/solr:/opt/mysolrhome solr:$SOLR_VERSION
  - docker ps -a
  - docker exec -it --user=root solr /bin/sh -c "chown -R solr:solr /opt/mysolrhome"
  - docker exec -it --user=solr solr bin/solr create_core -c default -d /opt/mysolrhome
  # Install Ruby dependencies
  - gem install bundler

matrix:
  allow_failures:
    - rvm: ruby-head

script:
  - ci/travis.sh

